version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - database:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=area-backend
      - MONGO_INITDB_ROOT_PASSWORD=mypassword

  server:
    container_name: server
    build:
      context: area-node/
    depends_on:
        - mongo
    ports:
      - "8080:3000"

  client_mobile:
    container_name: mobile_client
    build:
      context: area-expo/
    volumes:
      - shared_data:/pipe

  client_web:
    container_name: web_client
    build:
      context: area-react/
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:8081"
    volumes:
      - shared_data:/pipe

volumes:
  database:
  shared_data:
