version: '3'
services:
  server:
    container_name: server
    build:
      context: area-node/
    ports:
      - "8080:8080"
    volumes:
      - database:/data

  client_mobile:
    container_name: mobile_client
    build:
      context: area-expo/
    volumes:
      - shared_data:/shared

  client_web:
    container_name: web_client
    build:
      context: area-react/
    depends_on:
      - server
      - client_mobile
    ports:
      - "8081:8081"
    volumes:
      - shared_data:/shared

volumes:
  database:
  shared_data:
