name: apk-release

on: 
  push:
    branches:
      - devops
    tags:
      - '*'

jobs:
  create-tag:
    permissions: write-all
    runs-on: ubuntu-latest
    name: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate release tag
        id: tag
        run: |
          echo "::set-output name=release_tag::Release_$(date +"%Y.%m.%d_%H.%M")"
  
  build:
    runs-on: ubuntu-latest
    name: Build
    needs: create-tag
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name : Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Build
        working-directory: ./area-expo
        run: |
          eas build --platform android --profile production --no-wait --non-interactive --local
          mv build-*.apk area.apk

      - name: Create release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ needs.create-tag.outputs.release_tag }}
          name: ${{ needs.create-tag.outputs.release_tag }}
          artifacts: area.apk